### ISSUE TITLE
[Html&Css] 헤더 컴포넌트 

### ISSUE THREAD

**Issue by gomsaee** [FRONTENDSCHOOL10/109place#10]
## 🧾 제목
헤더 컴포넌트 마크업 & 스타일링

## ✅ TO-DO
- [x] 뒤로가기 버튼만 있는 헤더 만들기
- [x] 뒤로가기 x가 같이 있는 헤더 만들기
- [x] x만 있는 헤더만들기

## 📎 참고
![스크린샷 2024-07-07 오후 10 28 21](https://github.com/FRONTENDSCHOOL10/109place/assets/139846451/f462f350-d682-4e2b-9f9a-6931b69bd91f)
![스크린샷 2024-07-07 오후 10 23 04](https://github.com/FRONTENDSCHOOL10/109place/assets/139846451/14b0e4ea-4780-406b-8ae7-5246c9a5dd38)
![스크린샷 2024-07-07 오후 10 22 50](https://github.com/FRONTENDSCHOOL10/109place/assets/139846451/3391e0c5-42a1-47c8-bda4-45c5001dde22)
