### ISSUE TITLE
[Html&Css] 인풋&글자수 컴포넌트

### ISSUE THREAD

**Issue by A-Jamong** [FRONTENDSCHOOL10/109place#11]
## 🧾 제목
인풋&글자수 컴포넌트

## ✅ TO-DO
- [ ] 인풋&글자수 컴포넌트 마크업
- [ ] 인풋&글자수 컴포넌트 스타일링
- [ ] 글자수 카운트 기능 구현

## 📎 참고
<img width="273" alt="스크린샷 2024-07-07 오후 10 45 18" src="https://github.com/FRONTENDSCHOOL10/109place/assets/106497478/fa90012f-dad6-4f6b-bd3f-cb10ca084175">
<img width="409" alt="스크린샷 2024-07-07 오후 10 45 33" src="https://github.com/FRONTENDSCHOOL10/109place/assets/106497478/2d9b8d2f-2770-4190-aa36-4911989ee7b3">
