### ISSUE TITLE
[html&css] 메인 페이지(시작페이지)

### ISSUE THREAD

**Issue by A-Jamong** [FRONTENDSCHOOL10/109place#58]
## 🧾 제목
메인 페이지 마크업, 스타일링

## ✅ TO-DO
- [ ] 메인 페이지 마크업
- [ ] 메인 페이지 스타일링
- [ ] 임시로 다른 페이지들로 가는 버튼 추가

## 📎 참고

![스크린샷 2024-07-11 오전 6 57 06](https://github.com/FRONTENDSCHOOL10/109place/assets/106497478/0e246f80-d70c-4a29-a88b-7632383eb487)
